# Main Terraform configuration for Azure Storage Solution
# Generated by Terraform Repo Manager

terraform {
  required_version = ">=1.5"
  
  required_providers {
    azure = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

resource "azurerm_resource_group" "main" {
  name     = "rg-main-${var.environment}"
  location = "var.location"
  
  tags = var.default_tags
}
resource "azurerm_storage_account" "primary" {
  name                     = "stprimary${random_id.storage_suffix.hex}"
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  
  tags = var.default_tags
}
resource "azurerm_storage_account" "backup" {
  name                     = "stbackup${random_id.storage_suffix.hex}"
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "GRS"
  
  tags = var.default_tags
}
resource "azurerm_key_vault" "main" {
  name                = "kv-main-${random_id.kv_suffix.hex}"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  tenant_id          = data.azurerm_client_config.current.tenant_id
  
  sku_name = "standard"
  
  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id
    
    key_permissions = [
      "Get", "List", "Update", "Create", "Import", "Delete", "Recover", "Backup", "Restore"
    ]
    
    secret_permissions = [
      "Get", "List", "Set", "Delete", "Recover", "Backup", "Restore"
    ]
  }
  
  tags = var.default_tags
}
resource "azurerm_log_analytics_workspace" "main" {
  # Configure log_analytics_workspace here
  resource_group_name = azurerm_resource_group.main.name
  location           = azurerm_resource_group.main.location
  
  tags = var.default_tags
}
